package by.market.services.implementation.characteristic.list

import by.market.domain.characteristics.list.DoubleListCharacteristic
import by.market.repository.characteristic.list.DoubleListCharacteristicRepository
import by.market.services.implementation.characteristic.BaseCharacteristicService
import by.market.services.implementation.characteristic.BaseListCharacteristicService
import org.springframework.stereotype.Service

@Service
class DoubleListCharacteristicService(repository: DoubleListCharacteristicRepository)
    : BaseListCharacteristicService<DoubleListCharacteristic, DoubleListCharacteristicRepository>(repository)
