package by.market.facade.impl

import by.market.domain.characteristics.ProductCharacteristic
import by.market.dto.characteristics.ProductCharacteristicDTO
import by.market.mapper.characteristics.ProductCharacteristicMapper
import by.market.services.abstraction.ICharacteristicService
import by.market.services.impl.ProductCharacteristicService
import org.springframework.stereotype.Component

@Component
class ProductCharacteristicFacade(productCharacteristicService: ProductCharacteristicService, productCharacteristicMapper: ProductCharacteristicMapper)
    : AbstractFacade<ICharacteristicService<ProductCharacteristic>, ProductCharacteristicDTO, ProductCharacteristic>(productCharacteristicService, productCharacteristicMapper)
