package by.market.mapper.domain_dto_mapper.characteristics

import by.market.domain.characteristics.ProductCharacteristic
import by.market.mapper.IMapstructMapper
import by.market.mapper.dto.characteristics.ProductFrontEndCharacteristic

interface ProductCharacteristicMapper : IMapstructMapper<ProductFrontEndCharacteristic, ProductCharacteristic>
