package by.market.repository.characteristic

import by.market.domain.characteristics.list_values.StringListCharacteristic
import by.market.repository.AbstractCharacteristicRepository
import org.springframework.stereotype.Repository

@Repository
interface StringCharacteristicRepository : AbstractCharacteristicRepository<StringListCharacteristic, String>
